### ISSUE TITLE
执行valid.sh报错

### ISSUE THREAD

**Issue by lxdunan** [SCNU-RISLAB/MF-MOS#4]
作者您好我在执行valid.sh时报了下面的错误
Traceback (most recent call last):
  File "infer.py", line 6, in &lt;module&gt;
    from modules.user import *
  File "/home/lxdunan/code/MFmos/MF-MOS-main/modules/user.py", line 20, in &lt;module&gt;
    from modules.PointRefine.spvcnn import SPVCNN
  File "/home/lxdunan/code/MFmos/MF-MOS-main/modules/PointRefine/spvcnn.py", line 7, in &lt;module&gt;
    from torchsparse import PointTensor, SparseTensor
ImportError: cannot import name 'PointTensor' from 'torchsparse' (/home/lxdunan/anaconda3/anaconda3/envs/mfmos1/lib/python3.7/site-packages/torchsparse/__init__.py)

**Comment by s0um0r0y** [comment]
faced the same issue was fixed in a newer version of torchsparse

`pip install torch-sparse`
